#!/bin/sh

NC='\033[0m'
BOrange='\033[48;5;202;97m'
BRed='\033[1;97;41m'

NAME=$(git branch | grep '*' | sed 's/* //')
echo "Running pre-push hook on: ${BOrange}$NAME${NC}"

echo "${BOrange}1. Tests application${NC}"
bun test

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}1.... Tests failed${NC}"
    exit 1
fi